# Generated by Django 5.1.1 on 2024-10-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=200)),
                ('orderdate', models.DateField()),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phoneno', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('orderstatus', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('package_name', models.CharField(max_length=100, null=True)),
                ('package_price', models.FloatField(null=True)),
                ('package_description', models.CharField(max_length=500, null=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], default='pending', max_length=100)),
            ],
            options={
                'db_table': 'travel',
            },
        ),
        migrations.CreateModel(
            name='travel_agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'travel_agency',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstatus', models.CharField(default='pending', max_length=200)),
                ('transactionid', models.CharField(max_length=200)),
                ('paymentmode', models.CharField(default='paypal', max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.customer')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.customer')),
                ('packageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.package')),
                ('paymentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Touristapp.payment')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='travel_agencyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.travel_agency'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalamount', models.FloatField()),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.customer')),
                ('pacakgelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Touristapp.travel_agency')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
